#include <bits/stdc++.h>
using namespace std;
int n;
map<int,string>mp;
int main()
{
    mp[1] = "Washington";
    mp[2] = "Adams";
    mp[3] = "Jefferson";
    mp[4] = "Madison";
    mp[5] = "Monroe";
    mp[6] = "Adams";
    mp[7] = "Jackson";
    mp[8] = "Van Buren";
    mp[9] = "Harrison";
    mp[10] = "Tyler";
    mp[11] = "Polk";
    mp[12] = "Taylor";
    mp[13] = "Fillmore";
    mp[14] = "Pierce";
    mp[15] = "Buchanan";
    mp[16] = "Lincoln";
    mp[17] = "Johnson";
    mp[18] = "Grant";
    mp[19] = "Hayes";
    mp[20] = "Garfield";
    mp[21] = "Arthur";
    mp[22] = "Cleveland";
    mp[23] = "Harrison";
    mp[24] = "Cleveland";
    mp[25] = "McKinley";
    mp[26] = "Roosevelt";
    mp[27] = "Taft";
    mp[28] = "Wilson";
    mp[29] = "Harding";
    mp[30] = "Coolidge";
    mp[31] = "Hoover";
    mp[32] = "Roosevelt";
    mp[33] = "Truman";
    mp[34] = "Eisenhower";
    mp[35] = "Kennedy";
    mp[36] = "Johnson";
    mp[37] = "Nixon";
    mp[38] = "Ford";
    mp[39] = "Carter";
    mp[40] = "Reagan";
    cin>>n;
    cout<<mp[n]<<'\n';
    return 0;
}
